- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create the cloudformation stack
    cloudformation:
      stack_name: "splunk-vpc-flowlogs"
      state: present
      region: "{{ region }}"
      disable_roleback: false
      template: "{{ cloudformation_template_file_url }}"
      termination_protection: yes
      capabilities:
      - CAPABILITY_NAMED_IAM
      - CAPABILITY_AUTO_EXPAND
